# Generated by Django 6.0.6 on 2026-06-28 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("check_in", models.DateField(db_index=True)),
                ("check_out", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("special_requests", models.TextField(blank=True)),
                ("confirmation_code", models.CharField(db_index=True, max_length=12, unique=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="core.room",
                    ),
                ),
            ],
            options={
                "db_table": "core_bookings",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("room_service", "Room Service"),
                            ("housekeeping", "Housekeeping"),
                            ("maintenance", "Maintenance"),
                            ("concierge", "Concierge"),
                            ("wake_up_call", "Wake Up Call"),
                            ("transport", "Transport"),
                            ("spa", "Spa"),
                            ("dining", "Dining Reservation"),
                            ("laundry", "Laundry"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("voice_session_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("kafka_event_id", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="core.booking",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_service_requests",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("transcript", models.JSONField(default=list)),
                ("intent_detected", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("tts_characters", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("channel_name", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_sessions",
                        to="core.booking",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_requests_created",
                    models.ManyToManyField(blank=True, to="core.servicerequest"),
                ),
            ],
            options={
                "db_table": "core_voice_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("kafka_offset", models.BigIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["user", "timestamp"], name="idx_audit_user_ts"),
                    models.Index(
                        fields=["resource_type", "resource_id"], name="idx_audit_resource"
                    ),
                    models.Index(fields=["action", "timestamp"], name="idx_audit_action_ts"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["guest", "status"], name="idx_booking_guest_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["room", "check_in", "check_out"], name="idx_booking_room_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in", "check_out", "status"], name="idx_booking_dates_status"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["confirmation_code"], name="idx_booking_confirmation"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out__gt", models.F("check_in"))),
                name="check_out_after_check_in",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "priority", "service_type"], name="idx_sr_status_priority"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["guest", "status", "created_at"], name="idx_sr_guest_status"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["assigned_to", "status"], name="idx_sr_assigned_status"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["created_at", "service_type"], name="idx_sr_created_type"),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["guest", "status", "started_at"], name="idx_vs_guest_status"
            ),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(fields=["status", "started_at"], name="idx_vs_status_started"),
        ),
    ]
